### ISSUE TITLE
New API Document Structure

### ISSUE THREAD

**Issue by nrooney** [w3c-webmob/web-api-gap#6]
Last time we spoke we were thinking of making it similar to Dom’s "Standards for Web Applications on Mobile: current state and roadmap" document (http://www.w3.org/Mobile/mobile-web-app-state). 

What I want to figure out now is how we should structure the API Document. Effectively we'll be listing Native APIs and the platforms that support them, then we'll be stating somewhere whether they have been implemented on the web yet or not. So, we could group APIs by categories, as in the "Standards for Web Applications on Mobile: current state and roadmap" document.

If you guys agree with this - can we copy the structure from the "Standards for Web Applications on Mobile: current state and roadmap" document for our document? Or do you think we need to add or remove some categories. The categories currently are:

* Core Web Design and Development
  * Graphics and Layout
  * Device Adaptation
  * Forms
* Data storage
* Media and Real-Time Communications
* Usability and Accessibility
* Device Interaction
* Network Integration
* Application Lifecyle
* Payment and Services
* Performance & Tuning
* Security & Privacy

**Comment by leandroal** [comment]
Hi Natasha,
   I agree this, at least just to start it is ok for me. Once we start the work we can reorganize, if necessary.

   I have installed the pandoc and run the "make" command. We will keep you posted about our progress.

Thanks!

**Comment by d4n1** [comment]
I agree too, bu I think that we could add more 2 categories:
* Hardwares available
* Licenses
What do you thing about it?

Thanks.

**Comment by nrooney** [comment]
Sounds good to me! i will add!

**Comment by nrooney** [comment]
Ok, Given the great work @d4n1 has been doing, I have rejigged the categories for the document to be the following, can everyone let me know what they think? If you're happy with this, I can make the changes to the doc!

***Device Hardware Interaction***
battery.json
bluetooth-le.json
bluetooth.json
compass.json
accelerometer.json
magnetometer.json
nfc.json
wifi-wake.json
vibration.json
usb.json

***Device Apps Interaction***
calendar.json
contacts.json
push-notifications.json
globalization.json
ime.json (not sure about this here)
local-notification.json

***Geo***
geofencing.json
geolocation.json
indoor.json
globalization.json [2]

***Core Device, Task Management and Scheduling (Service?)***
background-scheduler.json
cpu-wake.json
device-info.json
screen-wake.json

***Media and Real-Time Communications***
camera-stream.json 
media-play.json
media-capture.json

***Storage, File and Cache Management***
file-transfer-background.json
file-transfer.json
secure-storage.json

***Network Information and Call/Message Management***
contacts.json [2]
telephony.json
network-info.json
messaging.json

***Payments***
in-app-billing.json
purchase.json

***Webview***
webview.json

**Comment by d4n1** [comment]
I like it. Because it makes the most simple and clear document.

**Comment by nrooney** [comment]
Cool thanks! Also - should "Core Device, Task Management and Scheduling (Service?)" be "Performance Tuning" @dontcallmedom

**Comment by leandroal** [comment]
What is the reference [2]?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Natasha RooneySent: segunda-feira, 25 de maio de 2015 08:17To: w3c-webmob/web-api-gapReply To: w3c-webmob/web-api-gapCc: Leandro Melo de SalesSubject: Re: [web-api-gap] New API Document Structure (#6)Cool thanks! Also - should "Core Device, Task Management and Scheduling (Service?)" be "Performance Tuning" @dontcallmedom 

—Reply to this email directly or view it on GitHub.

**Comment by dontcallmedom** [comment]
"Core Device, Task Management and Scheduling (Service?)" seems to match what is under "Application Lifecycle" in the roadmap doc at the moment @nrooney

**Comment by nrooney** [comment]
Application Lifecycle is good with me!
