### ISSUE TITLE
For each API

### ISSUE THREAD

**Issue by nrooney** [w3c-webmob/web-api-gap#7]
Hi all! For each API we will need to list / show qualities related to information the readers will want to see, are people happy to show these pieces of information for each API?:

* Feature: what feature the api has
* Description: of the api functions
* API / Platforms: list native platforms which use this api and the names they give it
* Related Web API: does a related web api exist?
* Working Group: which w3c working group is/should look after this?
* Current implementations: do any browsers do this already?
* Plugins: do any plugins do this already?
* Security Concern: short sentence on possible security concern of api
* Dependancies: what would the web need to have to support this?

**Comment by leandroal** [comment]
Hi Natasha
   Daniel and I started to investigate some of these info and we will ground this according to you what you specified in issue 6. Ok?

**Comment by d4n1** [comment]
Hi Natasha, we're investigating about it and we return feedback to you.

Thanks.

**Comment by nrooney** [comment]
Thanks guys!

**Comment by nrooney** [comment]
decision: log licensing when there is a strange situation for licensing! Add parameter "license" to express this in json for the appropriate platform

**Comment by d4n1** [comment]
All right, thanks Natasha.
